### ISSUE TITLE
tigervnc-1.1.0  Could not start Xvnc

### ISSUE THREAD

**Issue by goog** [TigerVNC/tigervnc#292]
i build vnc on a linux distribution based on centos 5 , with <code>sh {source_directory}/unix/build-xorg build</code>, and the bulid result seems ok, but starts fail
```bash
[root@localhost itsv]# vncserver :1
Could not start Xvnc.


Xvnc TigerVNC 1.1.0 - built Apr 12 2016 15:03:14
Copyright (C) 1999-2011 TigerVNC Team and many others (see README.txt)
See http://www.tigervnc.org for information on TigerVNC.
Underlying X server release 10605000, 
```

**Comment by CendioOssman** [comment]
1.1.0 is ancient so could you please try with a newer version? We also have builds for CentOS 5 for 1.6.0 which you can try.

**Comment by goog** [comment]
we need build it manually, so where to check the error log

**Comment by CendioOssman** [comment]
The error log is printed to the console (`Xvnc TigerVNC 1.1.0...` is from the log), so it doesn't seem any error was printed.

Again, please try 1.6.0. You might be hitting a bug that has long since been fixed. We can not help you with that old version.

**Comment by goog** [comment]
in build the vncviewer  
cmake -G "Unix Makefiles" ..   && make

```bash
Linking CXX executable vncviewer
/opt/centos/devtoolset-1.1/root/usr/libexec/gcc/x86_64-CentOS-linux/4.7.2/ld: /usr/local/lib/libfltk.a(Fl_Window_shape.o): undefined reference to symbol 'dlsym@@GLIBC_2.2.5'
/opt/centos/devtoolset-1.1/root/usr/libexec/gcc/x86_64-CentOS-linux/4.7.2/ld: note: 'dlsym@@GLIBC_2.2.5' is defined in DSO /lib64/libdl.so.2 so try adding it to the linker command line
/lib64/libdl.so.2: could not read symbols: Invalid operation
collect2: error: ld returned 1 exit status
make[2]: *** [vncviewer/vncviewer] error 1
make[1]: *** [vncviewer/CMakeFiles/vncviewer.dir/all] error 2
```

**Comment by CendioOssman** [comment]
Static linking requires special care, so I suggest you build your local FLTK with shared libraries enabled.

**Comment by goog** [comment]
when i rebuild the fltk with <code>--enable-shared</code>
also
```bash
/opt/centos/devtoolset-1.1/root/usr/libexec/gcc/x86_64-CentOS-linux/4.7.2/ld: /usr/local/lib/libfltk.a(Fl_Window_shape.o): undefined reference to symbol 'dlsym@@GLIBC_2.2.5'
/opt/centos/devtoolset-1.1/root/usr/libexec/gcc/x86_64-CentOS-linux/4.7.2/ld: note: 'dlsym@@GLIBC_2.2.5' is defined in DSO /lib64/libdl.so.2 so try adding it to the linker command line
/lib64/libdl.so.2: could not read symbols: 
```

**Comment by goog** [comment]
```bash
CMake Warning at unix/x0vncserver/CMakeLists.txt:24 (message):
  No XTest extension.  x0vncserver will be view-only.


CMake Warning at unix/x0vncserver/CMakeLists.txt:31 (message):
  No DAMAGE extension.  x0vncserver will have to use the slower polling
  method.


-- Configuring done
-- Generating done
-- Build files have been written to: /root/tigervnc-1.6.0/build

```
does this matter?

**Comment by goog** [comment]
[xorg build log ](https://github.com/TigerVNC/tigervnc/files/218509/build.log.txt)
shows <code>/usr/bin/ld: cannot find -lXext</code>
```bash
[root@localhost build]# find / -iname "libXext.so"
/usr/lib64/libXext.so
```

**Comment by CendioOssman** [comment]
Nobody is maintaining `build-xorg` so I'm not sure it actually works. Does it work if you just run cmake and make?

**Comment by goog** [comment]
does not work
```bash
[root@localhost build]# cmake ..
-- CMAKE_BUILD_TYPE = Release
-- VERSION = 1.6.0
-- BUILD_TIMESTAMP = 2016-04-14 15:52
-- 64-bit build
-- WARNING: You are not using libjpeg-turbo. Performance will suffer.
-- checking for module 'gnutls'
--   package 'gnutls' not found
-- Attempting to link static binaries...
-- Creating static libtool control file for target os
-- Creating static libtool control file for target rdr
-- Creating static libtool control file for target network
-- Creating static libtool control file for target Xregion
-- Creating static libtool control file for target rfb
CMake Warning at unix/x0vncserver/CMakeLists.txt:24 (message):
  No XTest extension.  x0vncserver will be view-only.


CMake Warning at unix/x0vncserver/CMakeLists.txt:31 (message):
  No DAMAGE extension.  x0vncserver will have to use the slower polling
  method.


-- Configuring done
-- Generating done
-- Build files have been written to: /root/tigervnc-1.6.0/build
[root@localhost build]# ls
a.out  CMakeCache.txt  CMakeFiles  cmake_install.cmake  cmake_uninstall.cmake  common  config.h  Makefile  media  po  release  tests  unix  vncviewer  xorg  xorg.build
[root@localhost build]# make
Scanning dependencies of target os
[  1%] Building C object common/os/CMakeFiles/os.dir/w32tiger.c.o
[  2%] Building CXX object common/os/CMakeFiles/os.dir/os.cxx.o
Linking CXX static library libos.a
[  2%] Built target os
Scanning dependencies of target rdr
[  2%] Building CXX object common/rdr/CMakeFiles/rdr.dir/Exception.cxx.o
[  3%] Building CXX object common/rdr/CMakeFiles/rdr.dir/FdInStream.cxx.o
/root/tigervnc-1.6.0/common/rdr/FdInStream.h:30: 警告：‘class rdr::FdInStreamBlockCallback’ 有虚函数却没有虚析构函数
[  4%] Building CXX object common/rdr/CMakeFiles/rdr.dir/FdOutStream.cxx.o
[  5%] Building CXX object common/rdr/CMakeFiles/rdr.dir/FileInStream.cxx.o
[  5%] Building CXX object common/rdr/CMakeFiles/rdr.dir/HexInStream.cxx.o
[  6%] Building CXX object common/rdr/CMakeFiles/rdr.dir/HexOutStream.cxx.o
[  7%] Building CXX object common/rdr/CMakeFiles/rdr.dir/InStream.cxx.o
[  8%] Building CXX object common/rdr/CMakeFiles/rdr.dir/RandomStream.cxx.o
[  8%] Building CXX object common/rdr/CMakeFiles/rdr.dir/TLSException.cxx.o
[  9%] Building CXX object common/rdr/CMakeFiles/rdr.dir/TLSInStream.cxx.o
[ 10%] Building CXX object common/rdr/CMakeFiles/rdr.dir/TLSOutStream.cxx.o
[ 11%] Building CXX object common/rdr/CMakeFiles/rdr.dir/ZlibInStream.cxx.o
[ 12%] Building CXX object common/rdr/CMakeFiles/rdr.dir/ZlibOutStream.cxx.o
Linking CXX static library librdr.a
[ 12%] Built target rdr
Scanning dependencies of target network
[ 13%] Building CXX object common/network/CMakeFiles/network.dir/TcpSocket.cxx.o
/root/tigervnc-1.6.0/common/rdr/FdInStream.h:30: 警告：‘class rdr::FdInStreamBlockCallback’ 有虚函数却没有虚析构函数
/root/tigervnc-1.6.0/common/network/Socket.h:80: 警告：‘class network::ConnectionFilter’ 有虚函数却没有虚析构函数
Linking CXX static library libnetwork.a
[ 13%] Built target network
Scanning dependencies of target Xregion
[ 13%] Building C object common/Xregion/CMakeFiles/Xregion.dir/Region.c.o
Linking C static library libXregion.a
[ 13%] Built target Xregion
Scanning dependencies of target rfb
[ 13%] Building CXX object common/rfb/CMakeFiles/rfb.dir/Blacklist.cxx.o
[ 14%] Building CXX object common/rfb/CMakeFiles/rfb.dir/CConnection.cxx.o
/root/tigervnc-1.6.0/common/rfb/UserPasswdGetter.h:21: 警告：‘class rfb::UserPasswdGetter’ 有虚函数却没有虚析构函数
[ 15%] Building CXX object common/rfb/CMakeFiles/rfb.dir/CMsgHandler.cxx.o
[ 16%] Building CXX object common/rfb/CMakeFiles/rfb.dir/CMsgReader.cxx.o
[ 16%] Building CXX object common/rfb/CMakeFiles/rfb.dir/CMsgWriter.cxx.o
[ 17%] Building CXX object common/rfb/CMakeFiles/rfb.dir/CSecurityPlain.cxx.o
/root/tigervnc-1.6.0/common/rfb/UserPasswdGetter.h:21: 警告：‘class rfb::UserPasswdGetter’ 有虚函数却没有虚析构函数
[ 18%] Building CXX object common/rfb/CMakeFiles/rfb.dir/CSecurityStack.cxx.o
/root/tigervnc-1.6.0/common/rfb/UserPasswdGetter.h:21: 警告：‘class rfb::UserPasswdGetter’ 有虚函数却没有虚析构函数
[ 19%] Building CXX object common/rfb/CMakeFiles/rfb.dir/CSecurityVeNCrypt.cxx.o
/root/tigervnc-1.6.0/common/rfb/UserPasswdGetter.h:21: 警告：‘class rfb::UserPasswdGetter’ 有虚函数却没有虚析构函数
[ 19%] Building CXX object common/rfb/CMakeFiles/rfb.dir/CSecurityVncAuth.cxx.o
/root/tigervnc-1.6.0/common/rfb/UserPasswdGetter.h:21: 警告：‘class rfb::UserPasswdGetter’ 有虚函数却没有虚析构函数
[ 20%] Building CXX object common/rfb/CMakeFiles/rfb.dir/ComparingUpdateTracker.cxx.o
[ 21%] Building CXX object common/rfb/CMakeFiles/rfb.dir/Configuration.cxx.o
[ 22%] Building CXX object common/rfb/CMakeFiles/rfb.dir/ConnParams.cxx.o
[ 22%] Building CXX object common/rfb/CMakeFiles/rfb.dir/CopyRectDecoder.cxx.o
/root/tigervnc-1.6.0/common/rfb/UserPasswdGetter.h:21: 警告：‘class rfb::UserPasswdGetter’ 有虚函数却没有虚析构函数
[ 23%] Building CXX object common/rfb/CMakeFiles/rfb.dir/Cursor.cxx.o
[ 24%] Building CXX object common/rfb/CMakeFiles/rfb.dir/Decoder.cxx.o
[ 25%] Building C object common/rfb/CMakeFiles/rfb.dir/d3des.c.o
[ 26%] Building CXX object common/rfb/CMakeFiles/rfb.dir/EncodeManager.cxx.o
/root/tigervnc-1.6.0/common/rfb/UserPasswdGetter.h:21: 警告：‘class rfb::UserPasswdGetter’ 有虚函数却没有虚析构函数
[ 26%] Building CXX object common/rfb/CMakeFiles/rfb.dir/Encoder.cxx.o
[ 27%] Building CXX object common/rfb/CMakeFiles/rfb.dir/HTTPServer.cxx.o
/root/tigervnc-1.6.0/common/rdr/FdInStream.h:30: 警告：‘class rdr::FdInStreamBlockCallback’ 有虚函数却没有虚析构函数
/root/tigervnc-1.6.0/common/network/Socket.h:80: 警告：‘class network::ConnectionFilter’ 有虚函数却没有虚析构函数
[ 28%] Building CXX object common/rfb/CMakeFiles/rfb.dir/HextileDecoder.cxx.o
/root/tigervnc-1.6.0/common/rfb/UserPasswdGetter.h:21: 警告：‘class rfb::UserPasswdGetter’ 有虚函数却没有虚析构函数
[ 29%] Building CXX object common/rfb/CMakeFiles/rfb.dir/HextileEncoder.cxx.o
/root/tigervnc-1.6.0/common/rfb/UserPasswdGetter.h:21: 警告：‘class rfb::UserPasswdGetter’ 有虚函数却没有虚析构函数
[ 29%] Building CXX object common/rfb/CMakeFiles/rfb.dir/JpegCompressor.cxx.o
[ 30%] Building CXX object common/rfb/CMakeFiles/rfb.dir/JpegDecompressor.cxx.o
[ 31%] Building CXX object common/rfb/CMakeFiles/rfb.dir/KeyRemapper.cxx.o
[ 32%] Building CXX object common/rfb/CMakeFiles/rfb.dir/LogWriter.cxx.o
[ 32%] Building CXX object common/rfb/CMakeFiles/rfb.dir/Logger.cxx.o
[ 33%] Building CXX object common/rfb/CMakeFiles/rfb.dir/Logger_file.cxx.o
[ 34%] Building CXX object common/rfb/CMakeFiles/rfb.dir/Logger_stdio.cxx.o
[ 35%] Building CXX object common/rfb/CMakeFiles/rfb.dir/Password.cxx.o
[ 35%] Building CXX object common/rfb/CMakeFiles/rfb.dir/PixelBuffer.cxx.o
[ 36%] Building CXX object common/rfb/CMakeFiles/rfb.dir/PixelFormat.cxx.o
[ 37%] Building CXX object common/rfb/CMakeFiles/rfb.dir/RREEncoder.cxx.o
/root/tigervnc-1.6.0/common/rfb/UserPasswdGetter.h:21: 警告：‘class rfb::UserPasswdGetter’ 有虚函数却没有虚析构函数
[ 38%] Building CXX object common/rfb/CMakeFiles/rfb.dir/RREDecoder.cxx.o
/root/tigervnc-1.6.0/common/rfb/UserPasswdGetter.h:21: 警告：‘class rfb::UserPasswdGetter’ 有虚函数却没有虚析构函数
[ 38%] Building CXX object common/rfb/CMakeFiles/rfb.dir/RawDecoder.cxx.o
/root/tigervnc-1.6.0/common/rfb/UserPasswdGetter.h:21: 警告：‘class rfb::UserPasswdGetter’ 有虚函数却没有虚析构函数
[ 39%] Building CXX object common/rfb/CMakeFiles/rfb.dir/RawEncoder.cxx.o
/root/tigervnc-1.6.0/common/rfb/UserPasswdGetter.h:21: 警告：‘class rfb::UserPasswdGetter’ 有虚函数却没有虚析构函数
[ 40%] Building CXX object common/rfb/CMakeFiles/rfb.dir/Region.cxx.o
[ 41%] Building CXX object common/rfb/CMakeFiles/rfb.dir/SConnection.cxx.o
/root/tigervnc-1.6.0/common/rfb/UserPasswdGetter.h:21: 警告：‘class rfb::UserPasswdGetter’ 有虚函数却没有虚析构函数
[ 42%] Building CXX object common/rfb/CMakeFiles/rfb.dir/SMsgHandler.cxx.o
[ 42%] Building CXX object common/rfb/CMakeFiles/rfb.dir/SMsgReader.cxx.o
[ 43%] Building CXX object common/rfb/CMakeFiles/rfb.dir/SMsgWriter.cxx.o
[ 44%] Building CXX object common/rfb/CMakeFiles/rfb.dir/ServerCore.cxx.o
[ 45%] Building CXX object common/rfb/CMakeFiles/rfb.dir/Security.cxx.o
/root/tigervnc-1.6.0/common/rfb/UserPasswdGetter.h:21: 警告：‘class rfb::UserPasswdGetter’ 有虚函数却没有虚析构函数
/root/tigervnc-1.6.0/common/rfb/SSecurityPlain.h:35: 警告：‘class rfb::PasswordValidator’ 有虚函数却没有虚析构函数
/root/tigervnc-1.6.0/common/rfb/SSecurityVncAuth.h:35: 警告：‘class rfb::VncAuthPasswdGetter’ 有虚函数却没有虚析构函数
/root/tigervnc-1.6.0/common/rfb/UserMsgBox.h:23: 警告：‘class rfb::UserMsgBox’ 有虚函数却没有虚析构函数
[ 45%] Building CXX object common/rfb/CMakeFiles/rfb.dir/SecurityServer.cxx.o
/root/tigervnc-1.6.0/common/rfb/UserPasswdGetter.h:21: 警告：‘class rfb::UserPasswdGetter’ 有虚函数却没有虚析构函数
/root/tigervnc-1.6.0/common/rfb/SSecurityPlain.h:35: 警告：‘class rfb::PasswordValidator’ 有虚函数却没有虚析构函数
/root/tigervnc-1.6.0/common/rfb/SSecurityVncAuth.h:35: 警告：‘class rfb::VncAuthPasswdGetter’ 有虚函数却没有虚析构函数
[ 46%] Building CXX object common/rfb/CMakeFiles/rfb.dir/SecurityClient.cxx.o
/root/tigervnc-1.6.0/common/rfb/UserPasswdGetter.h:21: 警告：‘class rfb::UserPasswdGetter’ 有虚函数却没有虚析构函数
/root/tigervnc-1.6.0/common/rfb/UserMsgBox.h:23: 警告：‘class rfb::UserMsgBox’ 有虚函数却没有虚析构函数
[ 47%] Building CXX object common/rfb/CMakeFiles/rfb.dir/SSecurityPlain.cxx.o
/root/tigervnc-1.6.0/common/rfb/UserPasswdGetter.h:21: 警告：‘class rfb::UserPasswdGetter’ 有虚函数却没有虚析构函数
/root/tigervnc-1.6.0/common/rfb/SSecurityPlain.h:35: 警告：‘class rfb::PasswordValidator’ 有虚函数却没有虚析构函数
[ 48%] Building CXX object common/rfb/CMakeFiles/rfb.dir/SSecurityStack.cxx.o
/root/tigervnc-1.6.0/common/rfb/UserPasswdGetter.h:21: 警告：‘class rfb::UserPasswdGetter’ 有虚函数却没有虚析构函数
[ 48%] Building CXX object common/rfb/CMakeFiles/rfb.dir/SSecurityVncAuth.cxx.o
/root/tigervnc-1.6.0/common/rfb/UserPasswdGetter.h:21: 警告：‘class rfb::UserPasswdGetter’ 有虚函数却没有虚析构函数
/root/tigervnc-1.6.0/common/rfb/SSecurityVncAuth.h:35: 警告：‘class rfb::VncAuthPasswdGetter’ 有虚函数却没有虚析构函数
/root/tigervnc-1.6.0/common/rfb/SSecurityVncAuth.cxx: In member function ‘virtual void rfb::VncAuthPasswdParameter::getVncAuthPasswd(rfb::PlainPasswd*, rfb::PlainPasswd*)’:
/root/tigervnc-1.6.0/common/rfb/SSecurityVncAuth.cxx:119: 警告：提领类型双关的指针将破坏强重叠规则
[ 49%] Building CXX object common/rfb/CMakeFiles/rfb.dir/SSecurityVeNCrypt.cxx.o
/root/tigervnc-1.6.0/common/rfb/UserPasswdGetter.h:21: 警告：‘class rfb::UserPasswdGetter’ 有虚函数却没有虚析构函数
[ 50%] Building CXX object common/rfb/CMakeFiles/rfb.dir/ScaleFilters.cxx.o
[ 51%] Building CXX object common/rfb/CMakeFiles/rfb.dir/Timer.cxx.o
/root/tigervnc-1.6.0/common/rfb/Timer.h:45: 警告：‘struct rfb::Timer::Callback’ 有虚函数却没有虚析构函数
[ 51%] Building CXX object common/rfb/CMakeFiles/rfb.dir/TightDecoder.cxx.o
/root/tigervnc-1.6.0/common/rfb/UserPasswdGetter.h:21: 警告：‘class rfb::UserPasswdGetter’ 有虚函数却没有虚析构函数
[ 52%] Building CXX object common/rfb/CMakeFiles/rfb.dir/TightEncoder.cxx.o
/root/tigervnc-1.6.0/common/rfb/UserPasswdGetter.h:21: 警告：‘class rfb::UserPasswdGetter’ 有虚函数却没有虚析构函数
[ 53%] Building CXX object common/rfb/CMakeFiles/rfb.dir/TightJPEGEncoder.cxx.o
/root/tigervnc-1.6.0/common/rfb/UserPasswdGetter.h:21: 警告：‘class rfb::UserPasswdGetter’ 有虚函数却没有虚析构函数
[ 54%] Building CXX object common/rfb/CMakeFiles/rfb.dir/UpdateTracker.cxx.o
[ 55%] Building CXX object common/rfb/CMakeFiles/rfb.dir/VNCSConnectionST.cxx.o
/root/tigervnc-1.6.0/common/rdr/FdInStream.h:30: 警告：‘class rdr::FdInStreamBlockCallback’ 有虚函数却没有虚析构函数
/root/tigervnc-1.6.0/common/network/Socket.h:80: 警告：‘class network::ConnectionFilter’ 有虚函数却没有虚析构函数
/root/tigervnc-1.6.0/common/rfb/UserPasswdGetter.h:21: 警告：‘class rfb::UserPasswdGetter’ 有虚函数却没有虚析构函数
/root/tigervnc-1.6.0/common/rfb/Timer.h:45: 警告：‘struct rfb::Timer::Callback’ 有虚函数却没有虚析构函数
[ 55%] Building CXX object common/rfb/CMakeFiles/rfb.dir/VNCServerST.cxx.o
/root/tigervnc-1.6.0/common/rfb/UserPasswdGetter.h:21: 警告：‘class rfb::UserPasswdGetter’ 有虚函数却没有虚析构函数
/root/tigervnc-1.6.0/common/rfb/Timer.h:45: 警告：‘struct rfb::Timer::Callback’ 有虚函数却没有虚析构函数
/root/tigervnc-1.6.0/common/rdr/FdInStream.h:30: 警告：‘class rdr::FdInStreamBlockCallback’ 有虚函数却没有虚析构函数
/root/tigervnc-1.6.0/common/network/Socket.h:80: 警告：‘class network::ConnectionFilter’ 有虚函数却没有虚析构函数
[ 56%] Building CXX object common/rfb/CMakeFiles/rfb.dir/ZRLEEncoder.cxx.o
/root/tigervnc-1.6.0/common/rfb/UserPasswdGetter.h:21: 警告：‘class rfb::UserPasswdGetter’ 有虚函数却没有虚析构函数
[ 57%] Building CXX object common/rfb/CMakeFiles/rfb.dir/ZRLEDecoder.cxx.o
/root/tigervnc-1.6.0/common/rfb/UserPasswdGetter.h:21: 警告：‘class rfb::UserPasswdGetter’ 有虚函数却没有虚析构函数
[ 58%] Building CXX object common/rfb/CMakeFiles/rfb.dir/encodings.cxx.o
[ 58%] Building CXX object common/rfb/CMakeFiles/rfb.dir/util.cxx.o
[ 59%] Building CXX object common/rfb/CMakeFiles/rfb.dir/Logger_syslog.cxx.o
[ 60%] Building CXX object common/rfb/CMakeFiles/rfb.dir/CSecurityTLS.cxx.o
/root/tigervnc-1.6.0/common/rfb/UserPasswdGetter.h:21: 警告：‘class rfb::UserPasswdGetter’ 有虚函数却没有虚析构函数
/root/tigervnc-1.6.0/common/rfb/UserMsgBox.h:23: 警告：‘class rfb::UserMsgBox’ 有虚函数却没有虚析构函数
[ 61%] Building CXX object common/rfb/CMakeFiles/rfb.dir/SSecurityTLS.cxx.o
/root/tigervnc-1.6.0/common/rfb/UserPasswdGetter.h:21: 警告：‘class rfb::UserPasswdGetter’ 有虚函数却没有虚析构函数
Linking CXX static library librfb.a
[ 61%] Built target rfb
Scanning dependencies of target tx
[ 62%] Building CXX object unix/tx/CMakeFiles/tx.dir/TXWindow.cxx.o
/root/tigervnc-1.6.0/unix/tx/TXWindow.h:41: 警告：‘class TXDeleteWindowCallback’ 有虚函数却没有虚析构函数
/root/tigervnc-1.6.0/unix/tx/TXWindow.h:49: 警告：‘class TXEventHandler’ 有虚函数却没有虚析构函数
/root/tigervnc-1.6.0/unix/tx/TXWindow.h:57: 警告：‘class TXGlobalEventHandler’ 有虚函数却没有虚析构函数
Linking CXX static library libtx.a
[ 62%] Built target tx
Scanning dependencies of target vncconfig
[ 63%] Building C object unix/vncconfig/CMakeFiles/vncconfig.dir/buildtime.c.o
[ 63%] Building C object unix/vncconfig/CMakeFiles/vncconfig.dir/vncExt.c.o
[ 64%] Building CXX object unix/vncconfig/CMakeFiles/vncconfig.dir/vncconfig.cxx.o
/root/tigervnc-1.6.0/common/rfb/Timer.h:45: 警告：‘struct rfb::Timer::Callback’ 有虚函数却没有虚析构函数
/root/tigervnc-1.6.0/unix/tx/TXWindow.h:41: 警告：‘class TXDeleteWindowCallback’ 有虚函数却没有虚析构函数
/root/tigervnc-1.6.0/unix/tx/TXWindow.h:49: 警告：‘class TXEventHandler’ 有虚函数却没有虚析构函数
/root/tigervnc-1.6.0/unix/tx/TXWindow.h:57: 警告：‘class TXGlobalEventHandler’ 有虚函数却没有虚析构函数
/root/tigervnc-1.6.0/unix/tx/TXCheckbox.h:42: 警告：‘class TXCheckboxCallback’ 有虚函数却没有虚析构函数
/root/tigervnc-1.6.0/unix/tx/TXButton.h:35: 警告：‘class TXButtonCallback’ 有虚函数却没有虚析构函数
[ 65%] Building CXX object unix/vncconfig/CMakeFiles/vncconfig.dir/QueryConnectDialog.cxx.o
/root/tigervnc-1.6.0/common/rfb/Timer.h:45: 警告：‘struct rfb::Timer::Callback’ 有虚函数却没有虚析构函数
/root/tigervnc-1.6.0/unix/tx/TXWindow.h:41: 警告：‘class TXDeleteWindowCallback’ 有虚函数却没有虚析构函数
/root/tigervnc-1.6.0/unix/tx/TXWindow.h:49: 警告：‘class TXEventHandler’ 有虚函数却没有虚析构函数
/root/tigervnc-1.6.0/unix/tx/TXWindow.h:57: 警告：‘class TXGlobalEventHandler’ 有虚函数却没有虚析构函数
/root/tigervnc-1.6.0/unix/tx/TXButton.h:35: 警告：‘class TXButtonCallback’ 有虚函数却没有虚析构函数
Linking CXX executable vncconfig
/usr/bin/ld: cannot find -lXext
collect2: ld 返回 1
make[2]: *** [unix/vncconfig/vncconfig] 错误 1
make[1]: *** [unix/vncconfig/CMakeFiles/vncconfig.dir/all] 错误 2
make: *** [all] 错误 2
[root@localhost build]# 
```

**Comment by goog** [comment]
how to add my library path to the existed cmake flie ?

**Comment by goog** [comment]
please tell me how to make it to start vncserver ?

**Comment by CendioOssman** [comment]
This does not look like a clean build. Please remove your `build` directory and start fresh. The default library path is provided by your compiler and should not need any modifications in our source.

Building Xvnc is not trivial, so I would again suggest you use our provided binaries if you are not used to these build tools.

**Comment by goog** [comment]
i wish you could guide me how to build it on centos 5 , thx.   also want to learn how to build it. although i have tried 3 days.

**Comment by CendioOssman** [comment]
CentOS 5 is a bit too old to work smoothly with TigerVNC so I'm afraid I do not have an easy guide for you. Please try using the mailing list instead. Perhaps some other CentOS 5 user has more information.

**Comment by goog** [comment]
```bash
cheng@ada ~/tigervnc-1.6.0/build $ make
[  2%] Built target os
[ 12%] Built target rdr
[ 13%] Built target network
[ 13%] Built target Xregion
[ 61%] Built target rfb
[ 62%] Built target tx
[ 65%] Built target vncconfig
[ 66%] Built target vncpasswd
[ 73%] Built target x0vncserver
[ 86%] Built target translations
Linking CXX executable vncviewer
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libfltk.a(Fl_x.o): undefined reference to symbol 'dlsym@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libdl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [vncviewer/vncviewer] Error 1
make[1]: *** [vncviewer/CMakeFiles/vncviewer.dir/all] Error 2
make: *** [all] Error 2
```
build in mint 17.3 also has issues.

**Comment by etienne678** [comment]
I had this issue too on ubuntu, and on my side it was the power management settings.
after i set them to never turn off the screen this never happened again.
