### ISSUE TITLE
TigerVNC 1.8.0 fails to build on macOS 10.12

### ISSUE THREAD

**Issue by fxcoudert** [TigerVNC/tigervnc#459]
TigerVNC 1.8.0 fails to build on macOS 10.11 and 10.12 with:

```
/tmp/tiger-vnc-20170516-24424-9114je/tigervnc-1.8.0/vncviewer/cocoa.mm:41:11: error: redefinition of 'kVK_RightCommand' as different kind of symbol
const int kVK_RightCommand = 0x36;
          ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/Carbon.framework/Frameworks/HIToolbox.framework/Headers/Events.h:276:3: note: previous definition is here
  kVK_RightCommand              = 0x36,
  ^
```

This code should be wrapped, for example, with `+#if !defined(MAC_OS_X_VERSION_10_12) || MAC_OS_X_VERSION_MAX_ALLOWED < MAC_OS_X_VERSION_10_12`. See https://bugs.winehq.org/show_bug.cgi?id=40830

**Comment by ilovezfs** [comment]
Note the build also fails on OS X 10.11 El Capitan when using Xcode 8.

**Comment by CendioOssman** [comment]
Ah, so they've fixed that bug in the API. Thanks for also finding a way to work around it. :)

**Comment by CendioOssman** [comment]
Can you check if they've also added a define for the menu key? It's on code 0x6E.

**Comment by ilovezfs** [comment]
It doesn't look like it.

**Comment by CendioOssman** [comment]
Fixed in 2b0a0ef0e6140a6c6a4c89813c98e3821df58f2b.
