### ISSUE TITLE
TigerVNC does not compile with GCC 6.4.0

### ISSUE THREAD

**Issue by awilfox** [TigerVNC/tigervnc#511]
While trying to build TigerVNC for Adélie Linux, which uses the GCC 6.4.0 compiler:

```
[  4%] Building CXX object common/os/CMakeFiles/os.dir/Mutex.cxx.o
/usr/src/packages/user/tigervnc/src/tigervnc-1.8.0/common/os/Mutex.cxx: In destructor 'os::Mutex::~Mutex()':
/usr/src/packages/user/tigervnc/src/tigervnc-1.8.0/common/os/Mutex.cxx:57:62: error: throw will always call terminate() [-Werror=terminate]
     throw rdr::SystemException("Failed to destroy mutex", ret);
                                                              ^
/usr/src/packages/user/tigervnc/src/tigervnc-1.8.0/common/os/Mutex.cxx:57:62: note: in C++11 destructors default to noexcept
/usr/src/packages/user/tigervnc/src/tigervnc-1.8.0/common/os/Mutex.cxx: In destructor 'os::Condition::~Condition()':
/usr/src/packages/user/tigervnc/src/tigervnc-1.8.0/common/os/Mutex.cxx:114:75: error: throw will always call terminate() [-Werror=terminate]
     throw rdr::SystemException("Failed to destroy condition variable", ret);
                                                                           ^
/usr/src/packages/user/tigervnc/src/tigervnc-1.8.0/common/os/Mutex.cxx:114:75: note: in C++11 destructors default to noexcept
cc1plus: all warnings being treated as errors
make[2]: *** [common/os/CMakeFiles/os.dir/build.make:63: common/os/CMakeFiles/os.dir/Mutex.cxx.o] Error 1
```

It seems that you would need `-std=c++98`, or else mark the dtor `throw` explicitly.  I would be happy to provide a patch, if you will specify which is preferable.

**Comment by CendioOssman** [comment]
It's probably better to stop throwing exceptions in the destructors. So just change them to ignore any failures.

**Comment by CendioOssman** [comment]
Fixed in ca0c5f571410d03fdbdf6e1b6cb18fcf79f26ea4.
