### ISSUE TITLE
Build fails with `dri3.c:29:10: fatal error: drm_fourcc.h: No such file or directory`

### ISSUE THREAD

**Issue by paulmenzel** [TigerVNC/tigervnc#740]
In [Arch Linux](https://aur.archlinux.org/packages/tigervnc-git/) and [Linux From Scratch 8.3](http://www.linuxfromscratch.org/blfs/view/8.3/xsoft/tigervnc.html) the build fails with the error below. It seems, this is a regression in TigerVNC 1.9.0, as it worked with 1.8.0.

```
Making all in dri3
make[1]: Entering directory '/dev/shm/bee-root/tigervnc/tigervnc-1.9.0-0/build/unix/xserver/dri3'
  CC       dri3.lo
  CC       dri3_screen.lo
  CC       dri3_request.lo
dri3.c:29:10: fatal error: drm_fourcc.h: No such file or directory
 #include <drm_fourcc.h>
          ^~~~~~~~~~~~~~
compilation terminated.
dri3_screen.c:32:10: fatal error: drm_fourcc.h: No such file or directory
 #include <drm_fourcc.h>
          ^~~~~~~~~~~~~~
compilation terminated.
dri3_request.c:33:10: fatal error: drm_fourcc.h: No such file or directory
 #include <drm_fourcc.h>
          ^~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:663: dri3.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [Makefile:663: dri3_screen.lo] Error 1
make[1]: *** [Makefile:663: dri3_request.lo] Error 1
make[1]: Leaving directory '/dev/shm/bee-root/tigervnc/tigervnc-1.9.0-0/build/unix/xserver/dri3'
```

The header files are present.

```
libdrm-2.4.94-0.x86_64
  /usr/include/libdrm/drm_fourcc.h
linux-headers-4.9.10-0.x86_64
  /usr/include/drm/drm_fourcc.h
```

Therefore, they need to be manually included.

    CFLAGS="$CFLAGS -I/usr/include/drm"

**Comment by CendioOssman** [comment]
I'm afraid this has nothing to do with TigerVNC. This is part of the Xorg build system which you integrate with TigerVNC. So any issues found there will have to be reported with the Xorg people as we have no control over them.
