### PR TITLE
Update build system so it will compile on Windows 10

### PR DESCRIPTION
**Pull request by mriphysicist**
With this commit, TigerVNC will compile for Windows using MSYS2, MinGW-w64 and Inno Setup 6.  The resulting binaries have some dll dependencies (even with BUILD_STATIC) and those are included in the installer.

Unfortunately, the latest version of MSYS2 and MinGW-w64 do not produce a working executable for Windows 7.

### CODE REVIEW

File: cmake/StaticBuild.cmake [hunk 1]
```diff
@@ -23,7 +23,10 @@ if(BUILD_STATIC)
 
   # gettext is included in libc on many unix systems
   if(NOT LIBC_HAS_DGETTEXT)
-    set(GETTEXT_LIBRARIES "-Wl,-Bstatic -lintl -liconv -Wl,-Bdynamic")
+    set(GETTEXT_LIBRARIES "-Wl,-Bstatic -lidn2 -lintl -lunistring -liconv -Wl,-Bdynamic")
```
Comment (CendioOssman) [inline cmake/StaticBuild.cmake:26]: I'm afraid this breaks some setups. Please have a look at #1032 and the discussion there.

File: release/tigervnc.iss.in [hunk 2]
```diff
@@ -24,10 +24,40 @@ LicenseFile=@CMAKE_SOURCE_DIR@\LICENCE.txt
...
+Source: "@WIN_DLL_PATH@libtasn1-6.dll"; DestDir: "{app}"; Flags: ignoreversion restartreplace; 
+Source: "@WIN_DLL_PATH@libunistring-2.dll"; DestDir: "{app}"; Flags: ignoreversion restartreplace;
+#endif
+#else
+Source: "@WIN_DLL_PATH@libffi-7.dll"; DestDir: "{app}"; Flags: ignoreversion restartreplace;
+Source: "@WIN_DLL_PATH@libp11-kit-0.dll"; DestDir: "{app}"; Flags: ignoreversion restartreplace; 
+Source: "@WIN_DLL_PATH@libunistring-2.dll"; DestDir: "{app}"; Flags: ignoreversion restartreplace;
+Source: "@WIN_DLL_PATH@libintl-8.dll"; DestDir: "{app}"; Flags: ignoreversion restartreplace; 
+Source: "@WIN_DLL_PATH@libiconv-2.dll"; DestDir: "{app}"; Flags: ignoreversion restartreplace;
+#endif
```
Comment (CendioOssman) [inline release/tigervnc.iss.in:53]: I'm afraid I don't think this is something we can really maintain. The list of DLLs and versions will vary depending on the build environment so this list will never be correct. :/

File: release/tigervnc.iss.in [hunk 3]
```diff
@@ -24,10 +24,40 @@ LicenseFile=@CMAKE_SOURCE_DIR@\LICENCE.txt
...
 #ifdef BUILD_WINVNC
 Source: "@CMAKE_CURRENT_BINARY_DIR@\win\winvnc\winvnc4.exe"; DestDir: "{app}"; Flags: ignoreversion restartreplace; 
 Source: "@CMAKE_CURRENT_BINARY_DIR@\win\wm_hooks\wm_hooks.dll"; DestDir: "{app}"; Flags: ignoreversion restartreplace; 
 Source: "@CMAKE_CURRENT_BINARY_DIR@\win\vncconfig\vncconfig.exe"; DestDir: "{app}"; Flags: ignoreversion restartreplace; 
+#ifndef BUILD_STATIC
+Source: "@CMAKE_CURRENT_BINARY_DIR@\win\vncconfig\vncconfig.exe"; DestDir: "{app}"; Flags: ignoreversion restartreplace; 
+#endif
```
Comment (CendioOssman) [inline release/tigervnc.iss.in:60]: Isn't this just a duplicate of the line above?

File: cmake/StaticBuild.cmake (hunk 1 above)
Comment (mriphysicist) [reply cmake/StaticBuild.cmake:26]: These are the changes @bphinz mentioned and uses in the official build process.  I offset the other changes based on the MinGW Makefiles generator.

File: release/tigervnc.iss.in (hunk 3 above)
Comment (mriphysicist) [reply release/tigervnc.iss.in:60]: Oops.  Thanks for catching that.  I don't have a lot of experience in pull requests.  Do I just amend my previous commit to fix it?

File: cmake/StaticBuild.cmake (hunk 1 above)
Comment (CendioOssman) [reply cmake/StaticBuild.cmake:26]: There is a suggested fix from me on that other issue. Could you test that?

File: release/tigervnc.iss.in (hunk 2 above)
Comment (CendioOssman) [reply release/tigervnc.iss.in:53]: Afraid not. I'm not familiar with how open source projects usually deal with Windows packaging. Should be possible to find some examples though?

File: release/tigervnc.iss.in (hunk 3 above)
Comment (CendioOssman) [reply release/tigervnc.iss.in:60]: Yup. And then you need to do a force push as you've altered the history.

Comment (mriphysicist) [reply release/tigervnc.iss.in]: OK.  I believe this item is fixed now.

File: cmake/StaticBuild.cmake (hunk 1 above)
Comment (mriphysicist) [reply cmake/StaticBuild.cmake:26]: I'll try it out and get back to you.

File: release/tigervnc.iss.in (hunk 2 above)
Comment (mriphysicist) [reply release/tigervnc.iss.in:53]: I will see what I can find.  It probably won't be quick.

File: cmake/StaticBuild.cmake (hunk 1 above)
Comment (mriphysicist) [reply cmake/StaticBuild.cmake]: Your approached worked with my build system.  I made the changes.

File: release/tigervnc.iss.in (hunk 2 above)
Comment (mriphysicist) [reply release/tigervnc.iss.in]: I am removing this section from my pull request for now.

File: cmake/StaticBuild.cmake [hunk 4]
```diff
@@ -23,7 +23,31 @@ if(BUILD_STATIC)
 
   # gettext is included in libc on many unix systems
   if(NOT LIBC_HAS_DGETTEXT)
-    set(GETTEXT_LIBRARIES "-Wl,-Bstatic -lintl -liconv -Wl,-Bdynamic")
+    FIND_LIBRARY(IDN2_LIBRARY NAMES idn2 libidn2
+      HINTS ${PC_GETTEXT_LIBDIR} ${PC_GETTEXT_LIBRARY_DIRS})
```
Comment (CendioOssman) [inline cmake/StaticBuild.cmake:27]: I'm fairly sure idn2 was for GnuTLS, not gettext. What did your link errors look like?

File: cmake/StaticBuild.cmake [hunk 5]
```diff
@@ -23,7 +23,31 @@ if(BUILD_STATIC)
...
+
+    if(UNISTRING_LIBRARY)
+      set(GETTEXT_LIBRARIES "${GETTEXT_LIBRARIES} -lunistring")
+    endif()
+    
+    set(GETTEXT_LIBRARIES "${GETTEXT_LIBRARIES} -liconv")
+
+    set(GETTEXT_LIBRARIES "${GETTEXT_LIBRARIES} -Wl,-Bdynamic")
+
+    if(CMAKE_GENERATOR STREQUAL "MinGW Makefiles" AND UNISTRING_LIBRARY)
```
Comment (CendioOssman) [inline cmake/StaticBuild.cmake:47]: We don't need to check what generator is used. This issue should appear for any build system.

File: cmake/StaticBuild.cmake [hunk 6]
```diff
@@ -134,6 +164,10 @@ if(BUILD_STATIC_GCC)
   endif()
   if(WIN32)
     set(STATIC_BASE_LIBRARIES "${STATIC_BASE_LIBRARIES} -lmingw32 -lgcc_eh -lgcc -lmoldname -lmingwex -lmsvcrt")
+    if(CMAKE_GENERATOR STREQUAL "MinGW Makefiles")
+      # pthread has to be statically linked after libraries above and before kernel32
+      set(STATIC_BASE_LIBRARIES "${STATIC_BASE_LIBRARIES} -Wl,-Bstatic -lpthread -Wl,-Bdynamic")
```
Comment (CendioOssman) [inline cmake/StaticBuild.cmake:169]: I still don't understand where this requirement comes from. pthread is not something that should be used on Windows. What error does this fix?

File: cmake/StaticBuild.cmake (hunk 4 above)
Comment (mriphysicist) [reply cmake/StaticBuild.cmake:27]: I'll look into this.  Would it be better for me to withdraw this pull request and submit more with smaller changes?

File: cmake/StaticBuild.cmake (hunk 6 above)
Comment (mriphysicist) [reply cmake/StaticBuild.cmake:169]: Here are the first relevant errors from my build without lpthread:
```
[ 59%] Linking CXX executable vncconfig.exe
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../lib\libgnutls.a(system.o):(.text+0x6): undefined reference to `clock_gettime'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0\libstdc++.a(eh_alloc.o):(.text$__tcf_0+0xc): undefined reference to `pthread_mutex_destroy'
...
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/libgcc_eh.a(emutls.o):(.text+0x5e): undefined reference to `pthread_mutex_init'
...
collect2.exe: error: ld returned 1 exit status
mingw32-make[2]: *** [win\vncconfig\CMakeFiles\vncconfig.dir\build.make:150: win/vncconfig/vncconfig.exe] Error 1
mingw32-make[1]: *** [CMakeFiles\Makefile2:637: win/vncconfig/CMakeFiles/vncconfig.dir/all] Error 2
mingw32-make: *** [Makefile:149: all] Error 2
```
It looks like MSYS2 requires pthread for libgnutls.a, libstdc++.a and libgcc_eh.a.  I have found many MSYS2 static libraries introduce many additional dependencies (including dynamic library dependencies).

File: cmake/StaticBuild.cmake (hunk 5 above)
Comment (mriphysicist) [reply cmake/StaticBuild.cmake:47]: I check the generator because the MSYS2 MinGW-w64 static libraries introduce a dynamic link dependency on the unistring library.  I don't want to break the official build process.  Do you know a better way to check it?  Should I just dynamically link for all builds?  I can't check the MXE build process right now.

File: cmake/StaticBuild.cmake (hunk 4 above)
Comment (mriphysicist) [reply cmake/StaticBuild.cmake]: You are correct.  I moved this portion of code.

File: cmake/StaticBuild.cmake (hunk 5 above)
Comment (mriphysicist) [reply cmake/StaticBuild.cmake]: I changed it to dynamic linking for all builds.

File: cmake/StaticBuild.cmake (hunk 6 above)
Comment (mriphysicist) [reply cmake/StaticBuild.cmake:164]: I found a cmake function to check for pthreads.  In the conversation view it was not updating for me.  However, if you check the actual changes the pthread library is only linked if cmake finds it is used.  The issue here is that msys2 mingw-w64 compiler compiles pthreads into gcc and the accompanying libraries.

**Comment by mriphysicist** [comment]
@CendioOssman Can this be accepted or are there more changes you would like to see?  I have additional fixes I want to submit after this is accepted.

File: cmake/StaticBuild.cmake [hunk 7]
```diff
@@ -58,6 +77,10 @@ if(BUILD_STATIC)
       set(GNUTLS_LIBRARIES "${GNUTLS_LIBRARIES} -lcrypt32")
       # And sockets
       set(GNUTLS_LIBRARIES "${GNUTLS_LIBRARIES} -lws2_32")
+      # link ncrypt and unistring statically
+      set(GNUTLS_LIBRARIES "${GNUTLS_LIBRARIES} -Wl,-Bstatic -lncrypt -Wl,-Bdynamic")
+      # p11-kit only available as dynamic library for MSYS2 on Windows and dynamic linking of unistring is required
```
Comment (CendioOssman) [inline cmake/StaticBuild.cmake:82]: This is problematic as we don't want to force a p11-kit dependency on people that are trying to get a properly static build.

I think we need to better detect if p11-kit is required by GnuTLS in such a case. And really test if a static library is missing.

File: cmake/StaticBuild.cmake [hunk 8]
```diff
@@ -58,6 +77,10 @@ if(BUILD_STATIC)
...
+      set(GNUTLS_LIBRARIES "${GNUTLS_LIBRARIES} -lp11-kit -lunistring")
```
Comment (CendioOssman) [inline cmake/StaticBuild.cmake:83]: These three aren't on all systems so they still need to be conditional.

File: cmake/StaticBuild.cmake [hunk 9]
```diff
@@ -24,7 +24,21 @@ if(BUILD_STATIC)
...
+    FIND_LIBRARY(UNISTRING_LIBRARY NAMES unistring libunistring
+      HINTS ${PC_GETTEXT_LIBDIR} ${PC_GETTEXT_LIBRARY_DIRS})
+
+    set(GETTEXT_LIBRARIES "-Wl,-Bstatic")
+
+    set(GETTEXT_LIBRARIES "${GETTEXT_LIBRARIES} -lintl")
+    
+    set(GETTEXT_LIBRARIES "${GETTEXT_LIBRARIES} -liconv")
+
+    set(GETTEXT_LIBRARIES "${GETTEXT_LIBRARIES} -Wl,-Bdynamic")
```
[the remark this answers is not in the document]
Comment (mriphysicist) [reply cmake/StaticBuild.cmake:44]: Fixed to be consistent with GnuTLS.

File: cmake/StaticBuild.cmake [hunk 10]
```diff
@@ -24,7 +24,21 @@ if(BUILD_STATIC)
...
+
+    if(UNISTRING_LIBRARY)
+      set(GETTEXT_LIBRARIES "${GETTEXT_LIBRARIES} -lunistring")
```
[the remark this answers is not in the document]
Comment (mriphysicist) [reply cmake/StaticBuild.cmake:47]: There is a problem with the unistring library in MSYS2 that prevents static linking from working.

File: cmake/StaticBuild.cmake (hunk 7 above)
Comment (mriphysicist) [reply cmake/StaticBuild.cmake:96]: I agree that would be more robust.  However, I don't know how to do that in CMAKE.  The current codebase doesn't compile for Windows without modification.  This will at least allow one setup to compile for Windows.  Unless you know of a setup that currently compiles without modification that this breaks?

File: cmake/StaticBuild.cmake (hunk 8 above)
Comment (mriphysicist) [reply cmake/StaticBuild.cmake]: I made p11-kit and unistring conditional.

File: cmake/StaticBuild.cmake (hunk 7 above)
Comment (CendioOssman) [reply cmake/StaticBuild.cmake:96]: This breaks at least our Linux mingw builds. So it would cause problems for existing users.

File: cmake/StaticBuild.cmake (hunk 10 above)
[the remark this answers is not in the document]
Comment (CendioOssman) [reply cmake/StaticBuild.cmake:47]: What specific problem? Is that static version of the library missing from MSYS2?

File: cmake/StaticBuild.cmake [hunk 11]
```diff
@@ -50,14 +74,32 @@ if(BUILD_STATIC)
...
+        HINTS ${PC_GNUTLS_LIBDIR} ${PC_GNUTLS_LIBRARY_DIRS})
+      FIND_LIBRARY(UNISTRING_LIBRARY NAMES unistring libunistring
+        HINTS ${PC_GNUTLS_LIBDIR} ${PC_GNUTLS_LIBRARY_DIRS})
+
       # GnuTLS uses various crypto-api stuff
       set(GNUTLS_LIBRARIES "${GNUTLS_LIBRARIES} -lcrypt32")
       # And sockets
       set(GNUTLS_LIBRARIES "${GNUTLS_LIBRARIES} -lws2_32")
+      # link ncrypt and unistring statically
+      set(GNUTLS_LIBRARIES "${GNUTLS_LIBRARIES} -Wl,-Bstatic -lncrypt -Wl,-Bdynamic")
```
Comment (CendioOssman) [inline cmake/StaticBuild.cmake:94]: ncrypt seems to be a system library? If so then it should be dynamically linked.

But I also don't see why it is needed. Is it GnuTLS in MSYS2 that requires it? What error do you get without that line?

File: cmake/StaticBuild.cmake (hunk 7 above)
Comment (mriphysicist) [reply cmake/StaticBuild.cmake:96]: This doesn't highlight the p11-kit code.  However, I did make the p11-kit include dependent on finding the p11-kit library.  That is not the same as determining if GnuTLS requires p11-kit.  However, is that sufficient to prevent breaking your build?

File: cmake/StaticBuild.cmake (hunk 10 above)
[the remark this answers is not in the document]
Comment (mriphysicist) [reply cmake/StaticBuild.cmake:47]: I receive the following linking errors when I link unistring statically.

```
[ 59%] Linking CXX executable vncconfig.exe
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../lib\libgnutls.a(str-iconv.o):(.text+0x2a0): undefined reference to `__imp_uninorm_nfc'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../lib\libgnutls.a(str-unicode.o):(.text+0x127): undefined reference to `__imp_UC_CATEGORY_Ll'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../lib\libgnutls.a(str-unicode.o):(.text+0x155): undefined reference to `__imp_UC_CATEGORY_Lu'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../lib\libgnutls.a(str-unicode.o):(.text+0x17a): undefined reference to `__imp_UC_CATEGORY_Lo'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../lib\libgnutls.a(str-unicode.o):(.text+0x1a9): undefined reference to `__imp_UC_CATEGORY_Nd'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../lib\libgnutls.a(str-unicode.o):(.text+0x1d8): undefined reference to `__imp_UC_CATEGORY_Lm'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../lib\libgnutls.a(str-unicode.o):(.text+0x207): undefined reference to `__imp_UC_CATEGORY_Mn'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../lib\libgnutls.a(str-unicode.o):(.text+0x236): undefined reference to `__imp_UC_CATEGORY_Mc'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../lib\libgnutls.a(str-unicode.o):(.text+0x265): undefined reference to `__imp_UC_CATEGORY_Lt'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../lib\libgnutls.a(str-unicode.o):(.text+0x294): undefined reference to `__imp_UC_CATEGORY_Nl'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../lib\libgnutls.a(str-unicode.o):(.text+0x2c3): undefined reference to `__imp_UC_CATEGORY_No'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../lib\libgnutls.a(str-unicode.o):(.text+0x2f2): undefined reference to `__imp_UC_CATEGORY_Me'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../lib\libgnutls.a(str-unicode.o):(.text+0x321): undefined reference to `__imp_UC_CATEGORY_Sm'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../lib\libgnutls.a(str-unicode.o):(.text+0x350): undefined reference to `__imp_UC_CATEGORY_Sc'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../lib\libgnutls.a(str-unicode.o):(.text+0x37f): undefined reference to `__imp_UC_CATEGORY_So'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../lib\libgnutls.a(str-unicode.o):(.text+0x3ae): undefined reference to `__imp_UC_CATEGORY_Sk'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../lib\libgnutls.a(str-unicode.o):(.text+0x3dd): undefined reference to `__imp_UC_CATEGORY_Pc'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../lib\libgnutls.a(str-unicode.o):(.text+0x40c): undefined reference to `__imp_UC_CATEGORY_Pd'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../lib\libgnutls.a(str-unicode.o):(.text+0x43b): undefined reference to `__imp_UC_CATEGORY_Ps'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../lib\libgnutls.a(str-unicode.o):(.text+0x46a): undefined reference to `__imp_UC_CATEGORY_Pe'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../lib\libgnutls.a(str-unicode.o):(.text+0x499): undefined reference to `__imp_UC_CATEGORY_Pi'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../lib\libgnutls.a(str-unicode.o):(.text+0x4c8): undefined reference to `__imp_UC_CATEGORY_Pf'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../lib\libgnutls.a(str-unicode.o):(.text+0x4f7): undefined reference to `__imp_UC_CATEGORY_Po'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../lib\libgnutls.a(str-unicode.o):(.text+0x538): undefined reference to `__imp_UC_CATEGORY_Zs'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../lib\libgnutls.a(str-unicode.o):(.text+0x55a): undefined reference to `__imp_UC_CATEGORY_Cc'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../lib\libgnutls.a(str-unicode.o):(.text+0x5f3): undefined reference to `__imp_UC_CATEGORY_Zs'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../lib\libgnutls.a(str-unicode.o):(.text+0x856): undefined reference to `__imp_uninorm_nfkc'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../lib\libgnutls.a(str-unicode.o):(.text+0x978): undefined reference to `__imp_uninorm_nfc'
collect2.exe: error: ld returned 1 exit status
mingw32-make[2]: *** [win\vncconfig\CMakeFiles\vncconfig.dir\build.make:150: win/vncconfig/vncconfig.exe] Error 1
mingw32-make[1]: *** [CMakeFiles\Makefile2:637: win/vncconfig/CMakeFiles/vncconfig.dir/all] Error 2
mingw32-make: *** [Makefile:149: all] Error 2
```
I believe the cause is the unistring library requires the static libraries to be compiled separately from the dynamic libraries.  MSYS2 compiles the dynamic and static libraries at the same time.

One potential workaround is linking statically first and then linking dynamically.  This should cause the dynamic linking to only be required when static linking doesn't find everything it needs, right?

File: cmake/StaticBuild.cmake (hunk 11 above)
Comment (mriphysicist) [reply cmake/StaticBuild.cmake]: You are correct that ncrypt is a system library and needs to be linked dynamically.  I corrected that and included it on the same line as crypt32 a couple lines above.

It is required by GnuTLS in MSYS2.  I get the following linking errors without it:
```
[ 59%] Linking CXX executable vncconfig.exe
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../lib\libgnutls.a(keys-win.o):(.text+0x2e): undefined reference to `NCryptFreeObject'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../lib\libgnutls.a(keys-win.o):(.text+0xdd): undefined reference to `NCryptSignHash'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../lib\libgnutls.a(keys-win.o):(.text+0x128): undefined reference to `NCryptSignHash'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../lib\libgnutls.a(keys-win.o):(.text+0x3e4): undefined reference to `NCryptDecrypt'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../lib\libgnutls.a(keys-win.o):(.text+0x434): undefined reference to `NCryptDecrypt'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../lib\libgnutls.a(keys-win.o):(.text+0x1542): undefined reference to `NCryptFreeObject'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../lib\libgnutls.a(keys-win.o):(.text+0x1551): undefined reference to `NCryptFreeObject'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../lib\libgnutls.a(keys-win.o):(.text+0x156d): undefined reference to `NCryptOpenStorageProvider'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../lib\libgnutls.a(keys-win.o):(.text+0x16bb): undefined reference to `NCryptOpenKey'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../lib\libgnutls.a(keys-win.o):(.text+0x16f7): undefined reference to `NCryptGetProperty'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../lib\libgnutls.a(keys-win.o):(.text+0x185d): undefined reference to `NCryptFreeObject'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../lib\libgnutls.a(keys-win.o):(.text+0x2500): undefined reference to `NCryptDeleteKey'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../lib\libgnutls.a(keys-win.o):(.text+0x250a): undefined reference to `NCryptFreeObject'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../lib\libgnutls.a(sysrng-bcrypt.o):(.text+0x17): undefined reference to `BCryptGenRandom'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../lib\libgnutls.a(sysrng-bcrypt.o):(.text+0x89): undefined reference to `BCryptOpenAlgorithmProvider'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../lib\libgnutls.a(sysrng-bcrypt.o):(.text+0xea): undefined reference to `BCryptCloseAlgorithmProvider'
collect2.exe: error: ld returned 1 exit status
mingw32-make[2]: *** [win\vncconfig\CMakeFiles\vncconfig.dir\build.make:150: win/vncconfig/vncconfig.exe] Error 1
mingw32-make[1]: *** [CMakeFiles\Makefile2:637: win/vncconfig/CMakeFiles/vncconfig.dir/all] Error 2
mingw32-make: *** [Makefile:149: all] Error 2
```

**Comment by CendioOssman** [comment]
Sorry for dropping the ball here. Should be ready to merge so I'll do a final test and get it done.
