### PR TITLE
Apply patch from openSUSE to fix build with xorg-server 1.20

### PR DESCRIPTION
**Pull request by metalefty**
Originally authored by Stefan Dirsch (openSUSE xorg-maintainers).

Obtained from: https://build.opensuse.org/package/view_file/X11:XOrg/tigervnc/u_xorg-server-1.20.7-ddxInputThreadInit.patch

----

It fails to build with the following log if the patch isn't applied.

```
  CC       libvnccommon_la-qnum_to_xorgevdev.lo
  CC       libvnccommon_la-qnum_to_xorgkbd.lo
  CXXLD    libvnccommon.la
  CXXLD    Xvnc
ld: error: duplicate symbol: ddxInputThreadInit
>>> defined at xvnc.c
>>>            Xvnc-xvnc.o:(ddxInputThreadInit)
>>> defined at Input.c
>>>            libvnccommon_la-Input.o:(.text+0xDC0) in archive ./.libs/libvnccommon.a
c++: error: linker command failed with exit code 1 (use -v to see invocation)
*** Error code 1

Stop.
make[3]: stopped in /wrkdirs/usr/ports/net/tigervnc-server/work/tigervnc-1.11.0/unix/xserver/hw/vnc
*** Error code 1
*** Error code 1
*** Error code 1

Stop.
````

### CODE REVIEW

**Comment by metalefty** [comment]
Hmm, it works for me but CI is failing. Let me some more time to brush up the patch.

**Comment by CendioOssman** [comment]
This should already be fixed in the latest release via 920d9c4d6562ecabf79497bc901d50522d4bc661. What version of TigerVNC are you using?

**Comment by CendioOssman** [comment]
No response. Closing.
