### PR TITLE
Nettle4 compat

### LINKED ISSUE #2073: tigervnc build-error against nettle 4
TigerVNC fails to build against Nettle 4 with:
```
/build/reproducible-path/tigervnc-1.15.0+dfsg/common/rfb/CSecurityDH.cxx: In member function ‘void rfb::CSecurityDH::writeCredentials()’:
/build/reproducible-path/tigervnc-1.15.0+dfsg/common/rfb/CSecurityDH.cxx:129:23: error: invalid conversion from ‘int’ to ‘uint8_t*’ {aka ‘unsigned char*’} [-fpermissive]
  129 |   md5_digest(&md5Ctx, 16, key);
      |                       ^~
      |                       |
      |                       int
/build/reproducible-path/tigervnc-1.15.0+dfsg/common/rfb/CSecurityDH.cxx:129:13: error: too many arguments to function ‘void nettle_md5_digest(md5_ctx*, uint8_t*)’
  129 |   md5_digest(&md5Ctx, 16, key);
      |             ^
In file included from /build/reproducible-path/tigervnc-1.15.0+dfsg/common/rfb/CSecurityDH.cxx:35:
/usr/include/nettle/md5.h:72:1: note: declared here
   72 | md5_digest(struct md5_ctx *ctx,
      | ^~~~~~~~~~
```

(Test build was with v 1.6.0 but afaict the respective code is still present in GIT head.

cu Andreas

### PR DESCRIPTION
**Pull request by CendioZeijlon**
TODO:
- [x] Client builds with Nettle 3.10?
- [x] Client builds with Nettle 4.0?
- [x] Server builds with Nettle 3.10?
- [x] Server builds with Nettle 4.0?

There were a couple of places where we were using the old functionality that was removed. This needs some investigation. 
It looks like we are handling larger-than-expected-digest sizes properly. But let's be sure!

Closes #2073

### CODE REVIEW

File: common/rfb/CSecurityRSAAES.cxx [hunk 1]
```diff
@@ -301,31 +301,31 @@ void CSecurityRSAAES::setCipher()
...
     sha1_init(&ctx);
     sha1_update(&ctx, 16, clientRandom);
     sha1_update(&ctx, 16, serverRandom);
-    sha1_digest(&ctx, 16, key);
+    sha1_digest(&ctx, SHA1_DIGEST_SIZE, key);
     rais = new rdr::AESInStream(rawis, key, 128);
     sha1_init(&ctx);
     sha1_update(&ctx, 16, serverRandom);
     sha1_update(&ctx, 16, clientRandom);
-    sha1_digest(&ctx, 16, key);
```
Comment (CendioZeijlon) [inline common/rfb/CSecurityRSAAES.cxx:316]: Here, we have changed from storing a cropped digest to storing the full digest.

I suppose this is alright since we previously passed on the same size buffer, where the rest of it contained garbage since it wasn't zero initialized before.

**Comment by CendioZeijlon** [comment]
I think this is ready to merge. What do you think, @CendioHalim, @CendioOssman?

**Review by CendioOssman — APPROVED** [review]
